                <table id="Header">
                    <tr>
                        <td colspan="3" style="text-align: left;"><span>M</span>anuscript <span>I</span>llumination: <span>N</span>on-<span>I</span>nvasive <span>A</span>nalysis,</td>
                    </tr>
                    <tr>
                        <td class="MiniareCell">MINIARE</td>
                        <td style="width: 300px;">
                            <span>R</span>esearch <span>A</span>nd <span>E</span>xpertise<br />
                            <hr style="margin-top:15px;"/>
                        </td>
                        <td>&nbsp;</td>
                    </tr>
              <?php 
                   if ($_SERVER["SCRIPT_NAME"] == '/News.php') { ?>
      <tr><td colspan="3">
        <div style="padding:3px; margin-top:10px; background-color:#c74c28">
                    
                    <img src="./Images/251_crop.jpg" alt="/Images/251_crop.jpg" width="75px" style="float:left; padding:3px; padding-right:10px; width:75px;">
                    <h3 style="font-size:12pt; text-transform:none; color:#fff"><a href="exhibition_colour.php">COLOUR: The Art and Science of Illuminated Manuscripts</a><br/>

                    <span style="font-size:smaller">An exhibition at the Fitzwilliam Museum, 30 July - 30 December 2016</span>
                    </h3>

                    </div> 
                    </td>
                    </tr>
                    <?php 
                }?>
                </table>
<br clear="all"/>