                <a href="index.php"><img src="./Images/Logo.png" alt="Logo.png"></a>
                <br />
                <br />
                <p><a href="Project.php">The Project</a></p>
                <p><a href="Objectives.php">Objectives</a></p>
                <p><a href="News.php">News</a></p>
                <p><a href="People.php">About Us</a></p>
                <p><a href="WhyCambridge.php">Why Cambridge?</a></p>
                <p><a href="Support.php">Support Us</a></p>
                <p><a class="MailtoLink" href="index.php">Contact Us</a></p>
                <p><a href="Publications.php">Publications</a></p>
                <p><a href="exhibition_colour.php">Exhibition</a></p>
                <p><a href="Links.php">Links</a></p>
		<p><a href="Jobs.php">Jobs</a></p>
                <br />
                <p><img src="./Images/CambridgeUniversityLogo.png" alt="CambridgeUniversityLogo.png" /></p>
                <p><img src="./Images/FitzwilliamLogo.png" alt="FitzwilliamLogo.png" /></p>
